name: Publish Docker image
on:
  release:
    types: [published]

  push:
   branches:
     - master

jobs:
  build:
    name: Push Docker image to Docker Hub & Base Upgrade Install 
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login Docker Hub
        uses: docker/setup-buildx-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: yangzun/private-hugo-blog:tagname

      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
        with:
          host: ${{ secrets.BASE_HOST }}
          user: ${{ secrets.BASE_USER }}
          pass: ${{ secrets.BASE_PASS }}
          port: ${{ secrets.BASE_PORT }}
          connect_timeout: 10s
          script: |
            echo test